# Generated by Django 6.0.7 on 2026-08-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0003_remove_product_created_at_remove_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('shopkeeper', 'Shop Keeper')], default='customer', max_length=20),
        ),
    ]
