# Generated by Django on 2026-08-11
from django.db import migrations, models
import django.db.models.deletion
import OFFICE_MANAGER.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('TEAM_LEADER', 'Team Leader'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'office_manager_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('original_duration_days', models.PositiveIntegerField()),
                ('admin_assigned_duration_days', models.PositiveIntegerField()),
                ('start_date', models.DateField(default=OFFICE_MANAGER.models.get_current_date)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_projects', to='OFFICE_MANAGER.user')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to='OFFICE_MANAGER.user')),
            ],
            options={
                'db_table': 'office_manager_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('leader_assigned_duration_days', models.PositiveIntegerField()),
                ('start_date', models.DateField(default=OFFICE_MANAGER.models.get_current_date)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='ASSIGNED', max_length=20)),
                ('submission_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='OFFICE_MANAGER.user')),
                ('assigned_to_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='OFFICE_MANAGER.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='OFFICE_MANAGER.project')),
            ],
            options={
                'db_table': 'office_manager_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
