# Generated by Django 6.0.7 on 2026-08-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OFFICE_MANAGER', '0002_add_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_employees', to='OFFICE_MANAGER.user'),
        ),
    ]
