# Generated by Django 6.0.7 on 2026-08-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OFFICE_MANAGER', '0004_otpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
